version: "2"
exclude_patterns:
- "**/node_modules/"
- "**/__tests__/"
- "**/constants/"
- "src/registerNotifications.tsx"
- "src/registerReducers.ts"
- "src/registerListeners.ts"
- "src/ForceTaskCompletionPlugin.tsx"
- "src/setupTests.ts"
- "src/index.ts"
- "*.d.ts"
