name: plugin-force-task-completion
owner: liberty
slack: pb-a-liberty
configuration_opt_in_environments: true

staging:
  environment:
    NODE_ENV: staging

production:
  environment:
    NODE_ENV: production

tests:
  primary:
    - name: web
      command: tail -f /dev/null
      environment:
        NODE_ENV: "test"
  steps:
    - run:
        test: Fetch the CodeClimate test reporter
        command: wget -O cc-test-reporter https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
    - run:
        test: Make CodeClimate reporter executable
        command: chmod +x ./cc-test-reporter
    - run:
        test: Start Code Climate reporter
        command: ./cc-test-reporter before-build
    - run:
        test: Type Check
        command: npm run type-check
    - run:
        test: Unit Tests
        command: npm test
    - run:
        test: End Code Climate reporter
        command: ./cc-test-reporter after-build
